DROP TABLE IF EXISTS ITEM_SUBGROUPS1;
CREATE TABLE ITEM_SUBGROUPS1(
    CODE INT PRIMARY KEY AUTO_INCREMENT,
    ANAME VARCHAR(60),
    ENAME VARCHAR(60) NOT NULL,
    SUBGROUP_CODE INT NOT NULL,
    FOREIGN KEY(SUBGROUP_CODE) REFERENCES ITEM_SUBGROUPS(CODE)
)
