DROP TABLE IF EXISTS ITEMS;
CREATE TABLE ITEMS(
    CODE INT PRIMARY KEY AUTO_INCREMENT,
    ANAME VARCHAR(60),
    ENAME VARCHAR(60) NOT NULL,
    GROUP_CODE INT NOT NULL,
    SUBGROUP_CODE INT,
    SUBGROUP1_CODE INT,
    UNIT_CODE INT NOT NULL,
    UNIT_CODE_2 INT,
    UNIT_CODE_3 INT,
    BRAND_CODE INT,
    ITEM_DESC VARCHAR(100),
    AVAILABLE_QTY INT DEFAULT 0,
    FOREIGN KEY(UNIT_CODE) REFERENCES UNITS(CODE),
    FOREIGN KEY(UNIT_CODE_2) REFERENCES UNITS(CODE),
    FOREIGN KEY(UNIT_CODE_3) REFERENCES UNITS(CODE), 
    FOREIGN KEY(GROUP_CODE) REFERENCES ITEM_GROUPS(CODE),
    FOREIGN KEY(SUBGROUP_CODE) REFERENCES ITEM_SUBGROUPS(CODE),
    FOREIGN KEY(SUBGROUP1_CODE) REFERENCES ITEM_SUBGROUPS1(CODE),
    FOREIGN KEY(BRAND_CODE) REFERENCES ITEM_BRANDS(CODE) 
)
