DROP TABLE IF EXISTS ITEM_SUBGROUPS;
CREATE TABLE ITEM_SUBGROUPS(
    CODE INT PRIMARY KEY AUTO_INCREMENT,
    ANAME VARCHAR(60) NOT NULL,
    ENAME VARCHAR(60),
    GROUP_CODE INT NOT NULL,
    FOREIGN KEY(GROUP_CODE) REFERENCES ITEM_GROUPS(CODE)
)
